categories:
  Example:
    slot: 10
    icon: minecraft:barrier
    items:
      '1':
        id: minecraft:diamond
        price:
          item: minecraft:dirt
          count: 1
      '2':
        id: minecraft:diamond_block
        price:
          item: minecraft:diamond
          count: 9
      '3':
        id: minecraft:netherite_ingot
        price:
          item: minecraft:diamond
          count: 9
      '4':
        id: minecraft:netherite_block
        price:
          item: minecraft:diamond
          count: 81