name: Shop
version: '1.0'
main: de.thecitycrafter.shop.Main
api-version: '1.21'
commands:
  shop:
    description: "open Shop"
  shopadmin:
    permission: "shop.admin"
    description: "admin commands"
