name: Shop
version: '1.0'
main: de.thecitycrafter.shop.Main
api-version: '1.21'
commands:
  shop:
    description: "opens shop menu"
    permission: "shop.use"
  shopadmin:
    permission: "shop.admin"
    description: "configure shop menu"

permissions:
  shop.use:
    default: true
